#!/usr/bin/env python3

#script to launch Wine with the correct environment

from __future__ import print_function

import filecmp
import json
import os
import shutil
import errno
import struct
import subprocess
import sys
import tarfile

from filelock import FileLock

#To enable debug logging, copy "user_settings.sample.py" to "user_settings.py"
#and edit it if needed.

#The Steam-Bridge wont work with default wine-statging due
#to https://github.com/Tk-Glitch/PKGBUILDS/blob/master/wine-tkg-git/wine-tkg-patches/proton-tkg-staging.patch
#Please also make sure that dxvk and faudio exists _within_ the prefix

PFX="Proton: "
ld_path_var = "LD_LIBRARY_PATH"

def nonzero(s):
    return len(s) > 0 and s != "0"

def log(msg):
    sys.stderr.write(PFX + msg + os.linesep)
    sys.stderr.flush()

def run_wine(args):
    subprocess.call(args, env=env, stderr=lfile, stdout=lfile)

def makedirs(path):
    try:
        os.makedirs(path)
    except OSError:
        #already exists
        pass

def try_copy(src, dst):
    try:
        shutil.copy(src, dst)
    except PermissionError as e:
        if e.errno == errno.EPERM:
            #be forgiving about permissions errors; if it's a real problem, things will explode later anyway
            log('Error while copying to \"' + dst + '\": ' + e.strerror)
        else:
            raise

def real_copy(src, dst):
    if os.path.islink(src):
        os.symlink(os.readlink(src), dst)
    else:
        try_copy(src, dst)

def copydir(src, dst):
    for src_dir, dirs, files in os.walk(src):
        rel_dir = src_dir.replace(src, "", 1).lstrip('/')
        if len(rel_dir) > 0:
            rel_dir = rel_dir + "/"
        dst_dir = src_dir.replace(src, dst, 1)
        if not os.path.exists(dst_dir):
            os.makedirs(dst_dir)
        for dir_ in dirs:
            src_file = os.path.join(src_dir, dir_)
            dst_file = os.path.join(dst_dir, dir_)
            if os.path.islink(src_file) and not os.path.exists(dst_file):
                real_copy(src_file, dst_file)
        for file_ in files:
            src_file = os.path.join(src_dir, file_)
            dst_file = os.path.join(dst_dir, file_)
            if not os.path.exists(dst_file):
                real_copy(src_file, dst_file)

if not "STEAM_COMPAT_DATA_PATH" in os.environ:
    log("No compat data path?")
    sys.exit(1)

basedir = "/usr"
bindir = basedir + "/bin"
libdir = basedir + "/lib"
lib64dir = basedir + "/lib64"
fontsdir = basedir + "/share/fonts"
wine_path = bindir + "/wine"

protonbasedir = os.path.dirname(sys.argv[0])
protonlibdir = protonbasedir + "/dist"

dist_lock = FileLock(protonbasedir + "/dist.lock", timeout=-1)

env = dict(os.environ)
dlloverrides = {"steam.exe": "b"} #always use our special built-in steam.exe

if "HOST_LC_ALL" in env and len(env["HOST_LC_ALL"]) > 0:
    #steam sets LC_ALL=C to help some games, but Wine requires the real value
    #in order to do path conversion between win32 and host. steam sets
    #HOST_LC_ALL to allow us to use the real value.
    env["LC_ALL"] = env["HOST_LC_ALL"]
else:
    env.pop("LC_ALL", "")

#for performance, logging is disabled by default; override with user_settings.py
env["DXVK_LOG_LEVEL"] = "none"
env["WINEDEBUG"] = "-all"
env.pop("WINEARCH", "")

if ld_path_var in os.environ:
    env[ld_path_var] = lib64dir + ":" + libdir + ":" + protonlibdir + ":" + os.environ[ld_path_var]
else:
    env[ld_path_var] = lib64dir + ":" + libdir + ":" + protonlibdir

env["WINEDLLPATH"] = protonlibdir

if "PATH" in os.environ:
    env["PATH"] = bindir + ":" + os.environ["PATH"]
else:
    env["PATH"] = bindir

with dist_lock:
    if not os.path.isdir(protonbasedir + "/dist/share/default_pfx"):
        #make default prefix
        makedirs(protonbasedir + "/dist/share/default_pfx")
        env["WINEPREFIX"] = protonbasedir + "/dist/share/default_pfx"
        run_wine([wine_path, "wineboot"])
        run_wine([bindir + "/wineserver", "-w"])

prefix = os.environ["STEAM_COMPAT_DATA_PATH"] + "/pfx/"
env["WINEPREFIX"] = prefix

if "PROTON_LOG" in env and nonzero(env["PROTON_LOG"]):
    env["WINEDEBUG"] = "+timestamp,+pid,+tid,+seh,+debugstr,+loaddll,+mscoree"
    env["DXVK_LOG_LEVEL"] = "info"
    env["WINE_MONO_TRACE"] = "E:System.NotImplementedException"

#default wine-mono override for FNA games
env["WINE_MONO_OVERRIDES"] = "Microsoft.Xna.Framework.*,Gac=n"

#load environment overrides
if os.path.exists(protonbasedir + "/user_settings.py"):
    try:
        import user_settings
        env.update(user_settings.user_settings)
    except:
        log("************************************************")
        log("THERE IS AN ERROR IN YOUR user_settings.py FILE:")
        log("%s" % sys.exc_info()[1])
        log("************************************************")

def check_environment(env_name, config_name):
    if not env_name in env:
        return False
    if nonzero(env[env_name]):
        config_opts.add(config_name)
    else:
        config_opts.discard(config_name)
    return True

if "STEAM_COMPAT_CONFIG" in os.environ:
    config_opts = set(os.environ["STEAM_COMPAT_CONFIG"].split(","))
else:
    config_opts = set()

if "wined3d11" in config_opts:
    config_opts.add("wined3d")

if not check_environment("PROTON_USE_WINED3D", "wined3d"):
    check_environment("PROTON_USE_WINED3D11", "wined3d")
check_environment("PROTON_NO_D3D11", "nod3d11")
check_environment("PROTON_NO_D3D10", "nod3d10")
check_environment("PROTON_NO_ESYNC", "noesync")
check_environment("PROTON_FORCE_LARGE_ADDRESS_AWARE", "forcelgadd")
check_environment("PROTON_OLD_GL_STRING", "oldglstr")

if not "noesync" in config_opts:
    env["WINEESYNC"] = "1"

if "oldglstr" in config_opts:
    #mesa override
    env["MESA_EXTENSION_MAX_YEAR"] = "2003"
    #nvidia override
    env["__GL_ExtensionStringVersion"] = "17700"

if "forcelgadd" in config_opts:
    #forcelgadd should be used just for testing whether a game is helped by
    #setting LARGE_ADDRESS_AWARE. If it does, then add an AppDefault in the
    #registry, so that it doesn't impact every executable in the prefix.
    env["WINE_LARGE_ADDRESS_AWARE"] = "1"

lfile = None
if "SteamGameId" in env:
    if env["WINEDEBUG"] != "-all":
        lfile_path = os.environ["HOME"] + "/steam-" + os.environ["SteamGameId"] + ".log"
        if os.path.exists(lfile_path):
            os.remove(lfile_path)
        lfile = open(lfile_path, "w+")
        lfile.write("======================\n")
        lfile.write("Proton: Proton Lime (a.k.a. Local Wine)\n")
        lfile.write("SteamGameId: " + env["SteamGameId"] + "\n")
        lfile.write("Command: " + str(sys.argv[2:]) + "\n")
        lfile.write("======================\n")
        lfile.flush()
else:
    env["WINEDEBUG"] = "-all"


prefix_lock = FileLock(os.environ["STEAM_COMPAT_DATA_PATH"] + "/pfx.lock", timeout=-1)
with prefix_lock:
    if not os.path.exists(prefix + "/user.reg"):
        #copy default prefix into place
        copydir(protonbasedir + "/dist/share/default_pfx", prefix)

    #copy steam files into place
    if "STEAM_COMPAT_CLIENT_INSTALL_PATH" in os.environ:
        #modern steam client sets this
        steamdir = os.environ["STEAM_COMPAT_CLIENT_INSTALL_PATH"]
    else:
        #linux-only fallback, really shouldn't get here
        steamdir = os.environ["HOME"] + ".steam/root/"
    dst = prefix + "/drive_c/Program Files (x86)/"
    makedirs(dst + "Steam")
    filestocopy = ["steamclient.dll",
            "steamclient64.dll",
            "Steam.dll"]
    for f in filestocopy:
        if os.path.isfile(steamdir + "/legacycompat/" + f):
            dstfile = dst + "Steam/" + f
            if os.path.isfile(dstfile):
                os.remove(dstfile)
            try_copy(steamdir + "/legacycompat/" + f, dstfile)

if "nod3d11" in config_opts:
    dlloverrides["d3d11"] = ""
    if "dxgi" in dlloverrides:
        del dlloverrides["dxgi"]

if "nod3d10" in config_opts:
    dlloverrides["d3d10_1"] = ""
    dlloverrides["d3d10"] = ""
    dlloverrides["dxgi"] = ""

s = ""
for dll in dlloverrides:
    setting = dlloverrides[dll]
    if len(s) > 0:
        s = s + ";" + dll + "=" + setting
    else:
        s = dll + "=" + setting
if "WINEDLLOVERRIDES" in os.environ:
    env["WINEDLLOVERRIDES"] = os.environ["WINEDLLOVERRIDES"] + ";" + s
else:
    env["WINEDLLOVERRIDES"] = s

def dump_dbg_env(f):
    f.write("PATH=\"" + env["PATH"] + "\" \\\n")
    f.write("\tTERM=\"xterm\" \\\n") #XXX
    f.write("\tWINEDEBUG=\"-all\" \\\n")
    f.write("\tWINEDLLPATH=\"" + env["WINEDLLPATH"] + "\" \\\n")
    f.write("\t" + ld_path_var + "=\"" + env[ld_path_var] + "\" \\\n")
    f.write("\tWINEPREFIX=\"" + env["WINEPREFIX"] + "\" \\\n")
    if "WINEESYNC" in env:
        f.write("\tWINEESYNC=\"" + env["WINEESYNC"] + "\" \\\n")
    if "SteamGameId" in env:
        f.write("\tSteamGameId=\"" + env["SteamGameId"] + "\" \\\n")
    if "SteamAppId" in env:
        f.write("\tSteamAppId=\"" + env["SteamAppId"] + "\" \\\n")
    if "PROTON_VR_RUNTIME" in env:
        f.write("\tPROTON_VR_RUNTIME=\"" + env["PROTON_VR_RUNTIME"] + "\" \\\n")
    if "WINEDLLOVERRIDES" in env:
        f.write("\tWINEDLLOVERRIDES=\"" + env["WINEDLLOVERRIDES"] + "\" \\\n")
    if "STEAM_COMPAT_CLIENT_INSTALL_PATH" in env:
        f.write("\tSTEAM_COMPAT_CLIENT_INSTALL_PATH=\"" + env["STEAM_COMPAT_CLIENT_INSTALL_PATH"] + "\" \\\n")
    if "WINE_LARGE_ADDRESS_AWARE" in env:
        f.write("\tWINE_LARGE_ADDRESS_AWARE=\"" + env["WINE_LARGE_ADDRESS_AWARE"] + "\" \\\n")

def dump_dbg_scripts():
    exe_name = os.path.basename(sys.argv[2])

    tmpdir = env.get("PROTON_DEBUG_DIR", "/tmp") + "/proton_" + os.environ["USER"] + "/"
    makedirs(tmpdir)

    with open(tmpdir + "winedbg", "w") as f:
        f.write("#!/bin/bash\n")
        f.write("#Run winedbg with args\n\n")
        f.write("cd \"" + os.getcwd() + "\"\n")
        dump_dbg_env(f)
        f.write("\t\"" + wine_path + "\" winedbg \"$@\"\n")
    os.chmod(tmpdir + "winedbg", 0o755)

    with open(tmpdir + "winedbg_run", "w") as f:
        f.write("#!/bin/bash\n")
        f.write("#Run winedbg and prepare to run game or given program\n\n")
        f.write("cd \"" + os.getcwd() + "\"\n")
        f.write("DEF_CMD=(")
        first = True
        for arg in sys.argv[2:]:
            if first:
                f.write("\"" + arg + "\"")
                first = False
            else:
                f.write(" \"" + arg + "\"")
        f.write(")\n")
        dump_dbg_env(f)
        f.write("\t\"" + wine_path + "\" winedbg \"${@:-${DEF_CMD[@]}}\"\n")
    os.chmod(tmpdir + "winedbg_run", 0o755)

    with open(tmpdir + "gdb_attach", "w") as f:
        f.write("#!/bin/bash\n")
        f.write("#Run winedbg in gdb mode and auto-attach to already-running program\n\n")
        f.write("cd \"" + os.getcwd() + "\"\n")
        f.write("EXE_NAME=${1:-\"" + exe_name + "\"}\n")
        f.write("WPID_HEX=$(\"" + tmpdir + "winedbg\" --command 'info process' | grep -i \"$EXE_NAME\" | cut -f2 -d' ' | tr -d '0')\n")
        f.write("if [ -z \"$WPID_HEX\" ]; then \n")
        f.write("    echo \"Program does not appear to be running: \\\"$EXE_NAME\\\"\"\n")
        f.write("    exit 1\n")
        f.write("fi\n")
        f.write("WPID_DEC=$(printf %d 0x$WPID_HEX)\n")
        dump_dbg_env(f)
        f.write("\t\"" + wine_path + "\" winedbg --gdb $WPID_DEC\n")
    os.chmod(tmpdir + "gdb_attach", 0o755)

    with open(tmpdir + "gdb_run", "w") as f:
        f.write("#!/bin/bash\n")
        f.write("#Run winedbg in gdb mode and prepare to run game or given program\n\n")
        f.write("cd \"" + os.getcwd() + "\"\n")
        f.write("DEF_CMD=(")
        first = True
        for arg in sys.argv[2:]:
            if first:
                f.write("\"" + arg + "\"")
                first = False
            else:
                f.write(" \"" + arg + "\"")
        f.write(")\n")
        dump_dbg_env(f)
        f.write("\t\"" + wine_path + "\" winedbg --gdb \"${@:-${DEF_CMD[@]}}\"\n")
    os.chmod(tmpdir + "gdb_run", 0o755)

    with open(tmpdir + "run", "w") as f:
        f.write("#!/bin/bash\n")
        f.write("#Run game or given command in environment\n\n")
        f.write("cd \"" + os.getcwd() + "\"\n")
        f.write("DEF_CMD=(")
        first = True
        for arg in sys.argv[2:]:
            if first:
                f.write("\"" + arg + "\"")
                first = False
            else:
                f.write(" \"" + arg + "\"")
        f.write(")\n")
        dump_dbg_env(f)
        f.write("\t\"" + wine_path + "\" steam.exe \"${@:-${DEF_CMD[@]}}\"\n")
    os.chmod(tmpdir + "run", 0o755)

def run():
    if "PROTON_DUMP_DEBUG_COMMANDS" in env and nonzero(env["PROTON_DUMP_DEBUG_COMMANDS"]):
        try:
            dump_dbg_scripts()
        except OSError:
            log("Unable to write debug scripts! " + str(sys.exc_info()[1]))
    run_wine([wine_path, "steam"] + sys.argv[2:])

if sys.version_info[0] == 2:
    binary_stdout = sys.stdout
elif sys.version_info[0] == 3:
    binary_stdout = sys.stdout.buffer
else:
    raise Exception("Unsupported python version")

#determine mode
if sys.argv[1] == "run":
    #start target app
    run()
elif sys.argv[1] == "waitforexitandrun":
    #wait for wineserver to shut down
    run_wine([bindir + "/wineserver", "-w"])
    #then run
    run()
elif sys.argv[1] == "getcompatpath":
    #linux -> windows path
    path = subprocess.check_output([wine_path, "winepath", "-w", sys.argv[2]], env=env, stderr=lfile)
    binary_stdout.write(path)
elif sys.argv[1] == "getnativepath":
    #windows -> linux path
    path = subprocess.check_output([wine_path, "winepath", sys.argv[2]], env=env, stderr=lfile)
    binary_stdout.write(path)
else:
    log("Need a verb.")
    sys.exit(1)

sys.exit(0)

# vim: set syntax=python:
